version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27018:27017"  # Host:Container
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: activityapp

  api:
    image: node:18
    container_name: activity_api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:3000"  # Host:Container
    command: sh -c "npm install && npm run dev"
    environment:
      - MONGO_URI=mongodb://mongo:27017/activityapp
      - JWT_SECRET=your_super_secret
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo-data:
